version: '3.7'  # Especifica la versión de la sintaxis

services:
  # Servicio 1: Base de Datos MariaDB
  db:
    image: mariadb:10.5  # Imagen de la BD
    container_name: mariadb_prod # Nombre específico del contenedor
    volumes:
      - data_mysql:/var/lib/mysql # Monta un volumen para persistencia de datos
    environment: # Variables de entorno para configuración interna
      - MYSQL_ROOT_PASSWORD=supersecret
      - MYSQL_DATABASE=wordpress_db
      - MYSQL_USER=wp_user
      - MYSQL_PASSWORD=wp_secret
  
  # Servicio 2: Servidor Web WordPress
  web:
    image: wordpress:4.9.8 # Imagen de WordPress
    container_name: wordpress_prod
    depends_on:
      - db # Asegura que la DB inicie antes que WordPress
    volumes:
      - ./app_data:/var/www/html # Bind Mount para desarrollo/código
    environment: # Configuración de WP para conectarse a la BD
      - WORDPRESS_DB_HOST=db # Usa el nombre del servicio 'db' para la conexión DNS
      - WORDPRESS_DB_USER=wp_user
      - WORDPRESS_DB_PASSWORD=wp_secret
      - WORDPRESS_DB_NAME=wordpress_db
    ports:
      - 8080:80 # Mapeo de puertos: Host 8080 -> Contenedor 80

volumes:
  data_mysql: # Definición del volumen persistente para la DB