spring.datasource.url=jdbc:mariadb://serverless-us-central1.sysp0000.db2.skysql.com:4094/jugetes?sslMode=REQUIRED
spring.datasource.username=dbpgf39613271
spring.datasource.password=K5Cla2sEdyLjGW)1R2dOXZ
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect